import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QuotesContextProvider } from "@/app/context/QuotesContext";
import { ThemeProvider } from "@/app/components/theme-provider";
import { auth0 } from "@/lib/auth0";
import { Navbar } from "@/app/components/navbar"; // 1. Navbar'ı import ettik

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth0.getSession();
  const user = session?.user;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        {/* 2. Navbar bileşenini çağırdık */}
        <Navbar user={user} hasSession={!!session} />

        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <QuotesContextProvider>{children}</QuotesContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}