import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QuotesContextProvider } from "@/app/context/QuotesContext";
import { ThemeProvider } from "next-themes";
import { Button, ButtonSize, ButtonVariant } from '@/components/ui/button';
import { auth0 } from "@/lib/auth0";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth0.getSession();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <nav>
          <ul className="flex gap-10 justify-end max-w-7xl py-6">
            {session ? (
            <>
              <li>
              <Button asChild>
                <a href="/auth/logout">Settings</a>
              </Button>
              </li>
              <li>
              <Button asChild>
                <a href="/auth/logout">LogOut</a>
              </Button>
              </li>
            </>  
              ) : ( 
            <li className="flex gap-3">
              <Button asChild>
                 <a href="/auth/login">LogIn</a>
              </Button>
            </li>  
            )}
          </ul>
        </nav>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      <QuotesContextProvider>{children}</QuotesContextProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}
