
import { UserContext } from "@/app/context/UserContext.js";
import {userId} from "@/lib/auth";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({ children }) {
const user = {
  userId: userId,
  username: "Pınar Ertanç",
  email: "pinar@gmail.com"

}

  return (
      <UserContext value={{...user}}>{children}</UserContext>
  );
}
